server:
  port: 9527

spring:
  banner:
    location: banner.txt
    charset: UTF-8
  datasource:
    dynamic:
      hikari:
        min-idle: 5
        idle-timeout: 180000
        max-pool-size: 10
        pool-name: MyHikariCP
        max-lifetime: 1800000
        connection-timeout: 30000
        connection-test-query: SELECT 1
      primary: primary
      datasource:
        primary:
          username: root
          password: root
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
  aop:
    proxy-target-class: true


  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

mybatis-plus:
  type-aliases-package: classpath:com/neu/factory2/system/entity
  mapper-locations: classpath:mapper/system/*.xml
  configuration:
    jdbc-type-for-null: null

logging:
  level.org.springframework.boot.autoconfigure: error

